// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzzQjCPelQwrE1-KW5tFN6aoQR20ALtc',
    appId: '1:245630913139:web:your-web-app-id',
    messagingSenderId: '245630913139',
    projectId: 'fileperpus-b0ee6',
    authDomain: 'fileperpus-b0ee6.firebaseapp.com',
    storageBucket: 'fileperpus-b0ee6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQzzQjCPelQwrE1-KW5tFN6aoQR20ALtc',
    appId: '1:245630913139:android:246d59891fc33bff1a3806',
    messagingSenderId: '245630913139',
    projectId: 'fileperpus-b0ee6',
    storageBucket: 'fileperpus-b0ee6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQzzQjCPelQwrE1-KW5tFN6aoQR20ALtc',
    appId: '1:245630913139:ios:your-ios-app-id',
    messagingSenderId: '245630913139',
    projectId: 'fileperpus-b0ee6',
    storageBucket: 'fileperpus-b0ee6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQzzQjCPelQwrE1-KW5tFN6aoQR20ALtc',
    appId: '1:245630913139:ios:your-ios-app-id',
    messagingSenderId: '245630913139',
    projectId: 'fileperpus-b0ee6',
    storageBucket: 'fileperpus-b0ee6.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQzzQjCPelQwrE1-KW5tFN6aoQR20ALtc',
    appId: '1:245630913139:web:your-web-app-id',
    messagingSenderId: '245630913139',
    projectId: 'fileperpus-b0ee6',
    authDomain: 'fileperpus-b0ee6.firebaseapp.com',
    storageBucket: 'fileperpus-b0ee6.firebasestorage.app',
  );
}
